title_name = "Call of Duty: Modern Warfare 2"
title_id = "41560817" # AV-2071
hash = "A3FFB7C11B688FE5" # default_mp.xex
#media_id = "2C8C0267" # Disc (USA, Europe): http://redump.org/disc/11809

[[patch]]
    name = "Increase memory allocation"
    desc = "Patches PMem_Init to allocate additional memory."
    author = "mo"
    is_enabled = true

    [[patch.be16]]
        address = 0x823129FA
        value = 0x1E00

    [[patch.be16]]
        address = 0x82312A1E
        value = 0x1E00
