title_name = "Call of Duty 4: Modern Warfare"
title_id = "415607E6"                         # AV-2022
hash = "B4B0A3571D5160E2"                     # default.xex
#media_id = "15E8CF88" # Disc (USA, Europe): http://redump.org/disc/12660

[[patch]]
name = "Memory allocator expansion"
desc = "Increases the engine's primary memory allocation from 0x19700000 (~407 MB) to 0x1E000000 (~480 MB)."
author = "mo"
is_enabled = true

# PMem_Init - Updates memory allocation size for initialization
[[patch.be16]]
address = 0x82188F4A
value = 0x1E00       # Change 0x1970 → 0x1E00 (main allocation call)

[[patch.be16]]
address = 0x82188F5A
value = 0x1E00       # Change 0x1970 → 0x1E00 (secondary reference)
